FROM centos:latest
# error:
# https://stackoverflow.com/questions/70926799/centos-through-vm-no-urls-in-mirrorlist
# fix 
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
# set local language
RUN yum install -y glibc-langpack-en
RUN yum update -y

WORKDIR /usr/src/local/cli
COPY . .
# RUN ./build-aux/setup-Linux-centos-8.sh

# COPY ./build-aux/setup-manual.sh ./build-aux/setup-manual.sh
# COPY ./build-aux/setup-Linux.sh ./build-aux/setup-Linux.sh
# COPY ./build-aux/setup-Linux-centos-8.sh ./build-aux/setup-Linux-centos-8.sh
# RUN curl -sL https://raw.githubusercontent.com/openfido/cli/main/install.sh | bash